Change password
vfurmane/ft_transcendence pull request #53
Opened 2023-02-01 17:11 UTC by vfurmane

Need to implement logout

2023-02-02 11:01 UTC, maxenceeudier approved these changes

2023-02-02 12:51 UTC, vfurmane commented
Waiting to merge https://github.com/vfurmane/ft_transcendence/pull/54 and https://github.com/vfurmane/ft_transcendence/pull/55

2023-02-02 19:24 UTC, deblokc approved these changes

2023-02-09 10:23 UTC, savosaicic requested changes
Remove the update-password route in the UsersController

2023-02-09 16:07 UTC, soleraeus approved these changes

2023-02-09 17:07 UTC, deblokc approved these changes

2023-02-14 09:35 UTC, savosaicic approved these changes

2023-02-14 13:33 UTC, merged