(back) Get, update and delete profile picture
vfurmane/ft_transcendence pull request #69
Opened 2023-02-14 09:52 UTC by savosaicic

2023-02-14 15:38 UTC, vfurmane requested changes

2023-02-14 15:38 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +      );
It would be easier for the front-end to send the default image as is, instead of throwing an error.

2023-02-14 15:38 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +  @UseGuards(JwtAuthGuard)
Protecting this route makes it hard to fetch the profile picture, because it would require to use `fetch()` with the authorization header set.

2023-02-14 15:38 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +    @Param('id') id: string,
I think that the _id_ of the user should be retrieved from its JWT. Here, whoever is logged in can change the profile picture of anyone.

2023-02-14 15:38 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +  async deleteProfilePicture(@Param('id') id: string): Promise<void> {
Same, the _id_ of the user should be retrieved from its JWT.

2023-02-14 15:38 UTC, vfurmane commented on apps/api/src/users/users.service.ts
> +    this.profileRepository.save(userProfile);
You should use `await`

2023-02-16 08:22 UTC, vfurmane approved these changes

2023-02-16 08:22 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +  @Put(':id/update-profile-picture')
The `id` in the route becomes useless

2023-02-16 08:22 UTC, vfurmane commented on apps/api/src/users/users.controller.ts
> +  @Delete('/:id/delete-profile-picture')
Useless `id` too

2023-02-16 09:14 UTC, maxenceeudier approved these changes

2023-02-16 11:50 UTC, deblokc approved these changes

2023-02-16 14:24 UTC, soleraeus approved these changes
I agree with @vfurmane , ids are not necessary in the routes. Sounds fine otherwise

2023-02-16 19:14 UTC, merged